// components/FlightCard.vue
<script lang="ts">
import { format, intervalToDuration } from 'date-fns';
import utcToZonedTime from 'date-fns-tz/utcToZonedTime';
import 'material-icons/iconfont/material-icons.css';

export default {
  props: ['airline', 'flightNumber', 'departureAirport', 'departureTimestamp', 'departureTimezoneName', 'arrivalAirport', 'arrivalTimestamp', 'arrivalTimezoneName'],
  computed: {
    departureDate() {
      return format(utcToZonedTime(this.departureTimestamp, this.departureTimezoneName), 'yyyy-MM-dd');
    },
    departureTime() {
      return format(utcToZonedTime(this.departureTimestamp, this.departureTimezoneName), 'p');
    },
    arrivalDate() {
      return format(utcToZonedTime(this.arrivalTimestamp, this.arrivalTimezoneName), 'yyyy-MM-dd');
    },
    arrivalTime() {
      return format(utcToZonedTime(this.arrivalTimestamp, this.arrivalTimezoneName), 'p');
    },
    duration() {
      return intervalToDuration({
        start: new Date(this.departureTimestamp),
        end: new Date(this.arrivalTimestamp),
      });
    },
    delimiter() {
      if (
        (this.airline || this.flightNumber)
        && (this.duration.years || this.duration.months || this.duration.days
        || this.duration.hours || this.duration.minutes || this.duration.seconds)
      ) {
        return '|';
      }

      return null;
    },
  },
};
</script>

<template>
  <div class="flex items-center p-6 rounded-2xl shadow hover:shadow-lg transition-shadow">
    <div class="flex-1">
      <!-- Depart/Arrive -->
      <div class="flex">
        <!-- Depart -->
        <div class="mr-10 shrink">
          <div class="text-gray-600 text-xs uppercase">Depart</div>
          <div class="text-2xl">
            <span class="font-bold mr-4 text-emerald-700">{{ departureTime }}</span>
            <span class="font-light text-gray-600">{{ departureAirport }}</span>
          </div>
          <div class="font-light -mt-1 text-gray-500 text-[0.625rem]">{{ departureTimezoneName }}</div>
        </div>

        <!-- Arrive -->
        <div class="shrink">
          <div class="text-gray-600 text-xs uppercase">Arrive</div>
          <div class="text-2xl">
            <span class="font-bold mr-4 text-emerald-700">{{ arrivalTime }}</span>
            <span class="font-light text-gray-600">{{ arrivalAirport }}</span>
          </div>
          <div class="font-light -mt-1 text-gray-500 text-[0.625rem]">{{ arrivalTimezoneName }}</div>
        </div>
      </div>

      <!-- Flight Name -->
      <div class="font-light mt-6 text-emerald-700 text-xl">
        {{ airline ? `${airline.name} ${airline.code}` : '' }} {{ flightNumber }} {{ delimiter }} {{ duration.days ? duration.days + 'd' : '' }} {{ duration.hours ? duration.hours + 'h' : '' }} {{ duration.minutes ? duration.minutes + 'm' : '' }}
      </div>
    </div>
    <div class="flex-none text-center w-20">
        <span class="material-icons !text-4xl text-slate-300">flight</span>
      </div>
  </div>
</template>

<style scoped></style>

// components/FlightCard.tsx
import { format, intervalToDuration } from 'date-fns';
import utcToZonedTime from 'date-fns-tz/utcToZonedTime';
import 'material-icons/iconfont/material-icons.css';

export default function FlightCard({ airline, flightNumber, departureAirport, departureTimestamp, departureTimezoneName, arrivalAirport, arrivalTimestamp, arrivalTimezoneName }) {
  const departureDate = format(utcToZonedTime(departureTimestamp, departureTimezoneName), 'yyyy-MM-dd');
  const departureTime = format(utcToZonedTime(departureTimestamp, departureTimezoneName), 'p');
  const arrivalDate = format(utcToZonedTime(arrivalTimestamp, arrivalTimezoneName), 'yyyy-MM-dd');
  const arrivalTime = format(utcToZonedTime(arrivalTimestamp, arrivalTimezoneName), 'p');
  const duration = intervalToDuration({
    start: new Date(departureTimestamp),
    end: new Date(arrivalTimestamp),
  });
  const delimiter = (function() {
    if (
      (airline || flightNumber)
      && (duration.years || duration.months || duration.days
        || duration.hours || duration.minutes || duration.seconds)
    ) {
      return '|';
    }
    return null;
  })();

  return (
    <div className="flex items-center p-6 rounded-2xl shadow hover:shadow-lg transition-shadow">
      <div className="flex-1">
        {/* Depart/Arrive */}
        <div className="flex">
          {/* Depart */}
          <div className="mr-10 shrink">
            <div className="text-gray-600 text-xs uppercase">Depart</div>
            <div className="text-2xl">
              <span className="font-bold mr-4 text-emerald-700">{departureTime}</span>
              <span className="font-light text-gray-600">{departureAirport}</span>
            </div>
            <div className="font-light -mt-1 text-gray-500 text-[0.625rem]">{departureTimezoneName}</div>
          </div>

          {/* Arrive */}
          <div className="shrink">
            <div className="text-gray-600 text-xs uppercase">Arrive</div>
            <div className="text-2xl">
              <span className="font-bold mr-4 text-emerald-700">{arrivalTime}</span>
              <span className="font-light text-gray-600">{arrivalAirport}</span>
            </div>
            <div className="font-light -mt-1 text-gray-500 text-[0.625rem]">{arrivalTimezoneName}</div>
          </div>
        </div>

        {/* Flight Name */}
        <div className="font-light mt-6 text-emerald-700 text-xl">
          {airline && `${airline.name} ${airline.code}`} {flightNumber} {delimiter} {(duration.years > 0) && duration.years + 'y'} {(duration.months > 0) && duration.months + 'm'} {(duration.days > 0) && duration.days + 'd'} {(duration.hours > 0 ) && duration.hours + 'h'} {(duration.minutes > 0) && duration.minutes + 'm'}
        </div>
      </div>
      <div className="flex-none text-center w-20">
          <span className="material-icons !text-4xl text-slate-300">flight</span>
        </div>
    </div>
  );
}
