// components/NotFound.vue
<script lang="ts" setup>
const router = useRouter();

useHead({
  title: 'Not Found',
});
</script>

<template>
  <div class="pt-10 text-center">
    <span class="block text-indigo-600">404</span>
    <span class="block font-bold text-4xl">Page not found</span>

    <p class="font-light mb-6 text-gray-500">
      Sorry, we couldn't find the page you're looking for.
    </p>
    <NuxtLink
      v-on:click="router.go(-1)"
      class="cursor-pointer text-indigo-600 hover:text-indigo-700"
    >
      &larr; Go back
    </NuxtLink>
  </div>
</template>

<style scoped></style>

// components/NotFound.tsx
import { useRouter } from 'next/router';

export default function NotFound() {
  const router = useRouter();

  return (
    <div className="pt-10 text-center">
      <span className="block text-emerald-600">404</span>
      <span className="block font-bold text-4xl">Page not found</span>

      <p className="font-light mb-6 text-gray-500">
        Sorry, we couldn't find the page you're looking for.
      </p>
      <span
        onClick={router.back}
        className="cursor-pointer text-emerald-500 hover:text-emerald-400"
      >
        &larr; Go back
      </span>
    </div>
  );
}
