// components/StayForm.vue
<script lang="ts" setup>
import { format } from 'date-fns';
import utcToZonedTime from 'date-fns-tz/utcToZonedTime';
import zonedTimeToUtc from 'date-fns-tz/zonedTimeToUtc';
import 'material-icons/iconfont/material-icons.css';

const { $supabase } = useNuxtApp();

// Get current session
const session = $supabase.auth.session();

/**
 * Get any initialized props
 */

const props = defineProps([
  'stayUuid',
  'tripUuid',
  'initialName',
  'initialAddress',
  'initialLatitude',
  'initialLongitude',
  'initialConfirmationNumber',
  'initialCheckinTimestamp',
  'initialCheckoutTimestamp',
  'initialTimezoneName',
]);

const tripUuid = ref(props.tripUuid || null);
const confirmationNumber = ref(props.initialConfirmationNumber || null);
const checkinTimestamp = ref(props.initialCheckinTimestamp || null);
const checkoutTimestamp = ref(props.initialCheckoutTimestamp || null);
const timezoneName = ref(props.initialTimezoneName || null);
const location = ref(null);
const name = computed(() => {
  if (location.value) {
    return location.value.properties.name;
  }

  if (props.initialName) {
    return props.initialName;
  }

  return null;
});
const address = computed(() => {
  if (location.value) {
    const houseNumber = location.value.properties.housenumber ? `${location.value.properties.housenumber} ` : '';
    const street = location.value.properties.street ? `${location.value.properties.street}, ` : '';
    const city = location.value.properties.city ? `${location.value.properties.city}, ` : '';
    const state = location.value.properties.state ? `${location.value.properties.state}` : '';
    const postCode = location.value.properties.postcode ? ` ${location.value.properties.postcode}` : '';
    const country = location.value.properties.country ? `, ${location.value.properties.country}` : '';

    return houseNumber + street + city + state + postCode + country;
  }

  if (props.initialAddress) {
    return props.initialAddress;
  }

  return null;
});
const latitude = computed(() => {
  if (location.value) {
    return location.value.geometry.coordinates[1];
  }

  if (props.initialLatitude) {
    return props.initialLatitude;
  }

  return null;
});
const longitude = computed(() => {
  if (location.value) {
    return location.value.geometry.coordinates[0];
  }

  if (props.initialLongitude) {
    return props.initialLongitude;
  }

  return null;
});

/**
 * Calculate dates and times
 */

const checkinDate = checkinTimestamp.value ? ref(format(utcToZonedTime(checkinTimestamp.value, timezoneName.value), 'yyyy-MM-dd')) : ref(null);
const checkinTime = checkinTimestamp.value ? ref(format(utcToZonedTime(checkinTimestamp.value, timezoneName.value), 'HH:mm')) : ref(null);

const checkoutDate = checkoutTimestamp.value ? ref(format(utcToZonedTime(checkoutTimestamp.value, timezoneName.value), 'yyyy-MM-dd')) : ref(null);
const checkoutTime = checkoutTimestamp.value ? ref(format(utcToZonedTime(checkoutTimestamp.value, timezoneName.value), 'HH:mm')) : ref(null);

/**
 * Automatically set timezone
 */

watch(location, async () => {
  const { data } = await useFetch(`/api/timezones?lat=${latitude.value}&lon=${longitude.value}`);
  timezoneName.value = data.value[0];
});

/**
 * Handle form
 */

const loading = ref(false);
const successMessage = ref(null);
const errorMessage = ref(null);

async function updateStay() {
  errorMessage.value = null;
  loading.value = true;

  // Check required fields
  if (
    !tripUuid.value
    || !name.value
    || !checkinDate.value
    || !checkinTime.value
    || !checkoutDate.value
    || !checkoutTime.value
    || !timezoneName.value
  ) {
    loading.value = false;
    errorMessage.value = 'Assigned Trip, Name, Check-In Date, Check-In Time, Check-Out Date, Check-Out Time, and Timezone are required.';

    return;
  }

  const body = {
    tripUuid: tripUuid.value,
    name: name.value,
    address: address.value,
    latitude: latitude.value,
    longitude: longitude.value,
    confirmationNumber: confirmationNumber.value,
    checkinTimestamp: zonedTimeToUtc(`${checkinDate.value} ${checkinTime.value}`, timezoneName.value),
    checkoutTimestamp: zonedTimeToUtc(`${checkoutDate.value} ${checkoutTime.value}`, timezoneName.value),
    timezoneName: timezoneName.value,
  };

  const headers = { Authorization: `Bearer ${session.access_token}` };

  let response = null;
  let nextPath = null;

  try {
    // If id exists, update; otherwise, create new
    if (props.stayUuid) {
      response = await $fetch(`/api/stays/${props.stayUuid}`, { method: 'put', body, headers });
      nextPath = `/stays/${props.stayUuid}`;
      successMessage.value = 'The stay has been updated!';
    } else {
      response = await $fetch('/api/stays', { method: 'post', body, headers });
      nextPath = `/stays/${response.uuid}`;
      successMessage.value = 'The stay has been created!';
    }

    await navigateTo({
      path: nextPath,
    });
  } catch (error) {
    errorMessage.value = 'Uh oh, something went wrong. Please try again later.';
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div>
    <div v-if="loading">
      <Loader />
    </div>
    <div v-else-if="successMessage">
      <Alert type="success">
        {{ successMessage }}
      </Alert>
    </div>
    <div v-else>
      <Alert v-if="errorMessage" type="error">
        {{ errorMessage }}
      </Alert>

      <form v-on:submit.prevent="updateStay">
        <div class="mb-6">
          <label class="block font-medium mb-1 text-sm">Assigned Trip</label>
          <TripSelect v-model="tripUuid" />
        </div>

        <div class="mb-4">
          <label class="block font-medium mb-1 text-sm">Name</label>
          <LocationSearch v-model="location" v-bind:initialValue="name" add-class="w-full" />
        </div>

        <div class="flex gap-4 mb-6">
          <div class="grow shrink-0">
            <Input label="Address" type="text" add-class="w-full" v-model="address" disabled />
          </div>

          <div class="grow-0 shrink">
            <Input label="Timezone" v-model="timezoneName" required disabled />
          </div>
        </div>

        <div class="mb-6">
          <Input label="Confirmation Number" type="text"  v-model="confirmationNumber" />
        </div>

        <div class="flex gap-4 mb-6">
          <Input label="Check-In Date" type="date" v-model="checkinDate" required />

          <Input label="Check-In Time" type="time" v-model="checkinTime" required />
        </div>

        <div class="flex gap-4 mb-6">
          <Input label="Check-Out Date" type="date" v-model="checkoutDate" required />

          <Input
            label="Check-Out Time"
            type="time"
            add-class="w-full"
            v-model="checkoutTime"
            required
          />
        </div>

        <Button type="submit">Submit</Button>
      </form>
    </div>
  </div>
</template>

<style scoped></style>

// components/StayForm.tsx
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import { format } from 'date-fns';
import utcToZonedTime from 'date-fns-tz/utcToZonedTime';
import zonedTimeToUtc from 'date-fns-tz/zonedTimeToUtc';
import supabase from '@/lib/supabase';
import Alert from './Alert';
import Input from './Input';
import Loader from './Loader';
import LocationSearch from './LocationSearch';
import PrimaryButton from './PrimaryButton';
import TripSelect from './TripSelect';

export default function StayForm({
  stayUuid,
  initialTripUuid,
  initialName,
  initialAddress,
  initialLatitude,
  initialLongitude,
  initialConfirmationNumber,
  initialCheckinTimestamp,
  initialCheckoutTimestamp,
  initialTimezoneName
}) {
  const session = supabase.auth.session();

  /**
   * Get any initialized props
   */

  const [tripUuid, setTripUuid] = useState(initialTripUuid);
  const [name, setName] = useState(initialName);
  const [address, setAddress] = useState(initialAddress);
  const [latitude, setLatitude] = useState(initialLatitude);
  const [longitude, setLongitude] = useState(initialLongitude);
  const [confirmationNumber, setConfirmationNumber] = useState(initialConfirmationNumber);
  const [checkinTimestamp, setCheckinTimestamp] = useState(initialCheckinTimestamp);
  const [checkoutTimestamp, setCheckoutTimestamp] = useState(initialCheckoutTimestamp);
  const [timezoneName, setTimezoneName] = useState(initialTimezoneName);

  const [location, setLocation] = useState();

  // Account for delay of router query param from main page component
  useEffect(() => {
    setTripUuid(initialTripUuid);
  }, [initialTripUuid]);

  /**
   * Calculate dates and times
   */

  const [checkinDate, setCheckinDate] = checkinTimestamp ? useState(format(utcToZonedTime(checkinTimestamp, timezoneName), 'yyyy-MM-dd')) : useState(null);
  const [checkinTime, setCheckinTime] = checkinTimestamp ? useState(format(utcToZonedTime(checkinTimestamp, timezoneName), 'HH:mm')) : useState(null);

  const [checkoutDate, setCheckoutDate] = checkoutTimestamp ? useState(format(utcToZonedTime(checkoutTimestamp, timezoneName), 'yyyy-MM-dd')) : useState(null);
  const [checkoutTime, setCheckoutTime] = checkoutTimestamp ? useState(format(utcToZonedTime(checkoutTimestamp, timezoneName), 'HH:mm')) : useState(null);

  /**
   * Automatically set timezone and coordinates
   */

  async function getTimezone(latitude, longitude) {
    const { data } = await axios(`/api/timezones?lat=${latitude}&lon=${longitude}`);
    return data[0];
  }

  async function selectLocation(selected) {
    setLocation(selected);

    if (selected) {
      const houseNumber = selected.properties.housenumber ? `${selected.properties.housenumber} ` : '';
      const street = selected.properties.street ? `${selected.properties.street}, ` : '';
      const city = selected.properties.city ? `${selected.properties.city}, ` : '';
      const state = selected.properties.state ? `${selected.properties.state}` : '';
      const postCode = selected.properties.postcode ? ` ${selected.properties.postcode}` : '';
      const country = selected.properties.country ? `, ${selected.properties.country}` : '';
      setAddress(houseNumber + street + city + state + postCode + country);

      const latitude = selected.geometry.coordinates[1];
      setLatitude(latitude);

      const longitude = selected.geometry.coordinates[0];
      setLongitude(longitude);
    
      const timezoneName = await getTimezone(latitude, longitude);
      setTimezoneName(timezoneName);

      setName(selected.properties.name);
    }
  }

  const router = useRouter();

  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  /**
   * Handle form
   */

  async function updateStay(e) {
    e.preventDefault();

    // Check required fields
    if (
      !tripUuid
      || !name
      || !checkinDate
      || !checkinTime
      || !checkoutDate
      || !checkoutTime
      || !timezoneName
    ) {
      setLoading(false);
      setErrorMessage('Assigned Trip, Name, Check-In Date, Check-In Time, Check-Out Date, Check-Out Time, and Timezone are required.');

      return;
    }

    const body = {
      tripUuid,
      name,
      address,
      latitude,
      longitude,
      confirmationNumber,
      checkinTimestamp: zonedTimeToUtc(`${checkinDate} ${checkinTime}`, timezoneName),
      checkoutTimestamp: zonedTimeToUtc(`${checkoutDate} ${checkoutTime}`, timezoneName),
      timezoneName,
    };

    const headers = { Authorization: `Bearer ${session.access_token}` };

    let nextPath = null;

    try {
      // If id exists, update; otherwise, create new
      if (stayUuid) {
        await axios({ url: `/api/stays/${stayUuid}`, method: 'put', data: body, headers });
        nextPath = `/stays/${stayUuid}`;
        setSuccessMessage('The stay has been updated!');
      } else {
        const { data } = await axios({ url: '/api/stays', method: 'post', data: body, headers });
        nextPath = `/stays/${data.uuid}`;
        setSuccessMessage('The stay has been created!');
      }

      router.push(nextPath);
    } catch (error) {
      setErrorMessage('Uh oh, something went wrong. Please try again later.');
    } finally {
      setLoading(false);
    }
  }

  if (loading) {
    return (
      <Loader />
    );
  }

  if (successMessage) {
    return (
      <Alert type="success">
        {successMessage}
      </Alert>
    );
  }

  return (
    <div className="max-w-lg">
      {errorMessage &&
        <Alert type="error">
          {errorMessage}
        </Alert>
      }

      <form onSubmit={updateStay}>
        <div className="mb-6">
          <label className="block font-bold mb-1 text-xs uppercase">Assigned Trip</label>
          <TripSelect value={tripUuid} onChange={e => setTripUuid(e.target.value)} />
        </div>

        <div className="mb-4">
          <label className="block font-bold mb-1 text-xs uppercase">Name</label>
          <LocationSearch value={location} initialValue={name} onSelect={selectLocation} addClass="w-full" />
        </div>

        <div className="flex gap-4 mb-6">
          <div className="grow shrink-0">
            <Input label="Address" type="text" addClass="w-full" value={address} onChange={e => setAddress(e.target.value)} disabled />
          </div>

          <div className="grow-0 shrink">
            <Input label="Timezone" value={timezoneName} onChange={e => setTimezoneName(e.target.value)} required disabled />
          </div>
        </div>

        <div className="mb-6">
          <Input label="Confirmation Number" type="text" value={confirmationNumber} onChange={e => setConfirmationNumber(e.target.value)} />
        </div>

        <div className="flex gap-4 mb-6">
          <Input label="Check-In Date" type="date" value={checkinDate} onChange={e => setCheckinDate(e.target.value)} required />

          <Input label="Check-In Time" type="time" value={checkinTime} onChange={e => setCheckinTime(e.target.value)} required />
        </div>

        <div className="flex gap-4 mb-8">
          <Input label="Check-Out Date" type="date" value={checkoutDate} onChange={e => setCheckoutDate(e.target.value)} required />

          <Input
            label="Check-Out Time" type="time" addClass="w-full" value={checkoutTime} onChange={e => setCheckoutTime(e.target.value)} required />
        </div>

        <PrimaryButton type="submit">Submit</PrimaryButton>
      </form>
    </div>
  );
}
