// components/TripForm.tsx
import { useState } from 'react';
import { useRouter } from 'next/router';
import axios from 'axios';
import supabase from '@/lib/supabase';
import Alert from './Alert';
import Input from './Input';
import Loader from './Loader';
import PrimaryButton from './PrimaryButton';

// Get current session
const session = supabase.auth.session();

export default function TripForm({ initialName = '', tripUuid }) {
  const router = useRouter();

  const [loading, setLoading] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');
  const [successMessage, setSuccessMessage] = useState('');

  const [name, setName] = useState(initialName);

  /**
   * Handle form
   */

  async function updateTrip(e) {
    e.preventDefault();

    // Check required fields
    if (!name) {
      setLoading(false);
      setErrorMessage('Name is required.');
  
      return;
    }
  
    const body = {
      name,
    };
  
    const headers = {
      Authorization: `Bearer ${session.access_token}`,
    };
  
    let nextPath = null;
  
    try {
      // If id exists, update; otherwise, create new
      if (tripUuid) {
        await axios({ url: `/api/trips/${tripUuid}`, method: 'put', data: body, headers });
        nextPath = `/trips/${tripUuid}`;
        setSuccessMessage('The trip has been updated!');
      } else {
        const { data } = await axios({ url: '/api/trips', method: 'post', data: body, headers });
        nextPath = `/trips/${data.uuid}`;
        setSuccessMessage('The trip has been created!');
      }
  
      router.push(nextPath);
    } catch (error) {
      setErrorMessage('Uh oh, something went wrong. Please try again later.');
    } finally {
      setLoading(false);
    }
  }

  if (loading) {
    return (
      <Loader />
    );
  }

  if (successMessage) {
    return (
      <Alert type="success">
        {successMessage}
      </Alert>
    );
  }

  return (
    <div className="max-w-sm">
      {errorMessage && (
        <Alert type="error" addClass="mb-6">
          {errorMessage}
        </Alert>
      )}

      <form onSubmit={updateTrip}>
        <div className="mb-8">
          <Input label="Name" type="text" addClass="w-full" value={name} onChange={e => setName(e.target.value)} required />
        </div>

        <PrimaryButton type="submit">Submit</PrimaryButton>
      </form>
    </div>
  );
}

// components/TripForm.vue
<script lang="ts" setup>
const { $supabase } = useNuxtApp();

// Get current session
const session = $supabase.auth.session();

/**
 * Get any initialized props
 * */

const props = defineProps(['tripUuid', 'initialName']);

const name = ref(props.initialName || null);

/**
 * Handle form
 */

const loading = ref(false);
const successMessage = ref(null);
const errorMessage = ref(null);

async function updateTrip() {
  errorMessage.value = null;
  loading.value = true;

  // Check required fields
  if (!name.value) {
    loading.value = false;
    errorMessage.value = 'Name is required.';

    return;
  }

  const body = {
    name: name.value,
  };

  const headers = { Authorization: `Bearer ${session.access_token}` };

  let response = null;
  let nextPath = null;

  try {
    // If id exists, update; otherwise, create new
    if (props.tripUuid) {
      response = await $fetch(`/api/trips/${props.tripUuid}`, { method: 'put', body, headers });
      nextPath = `/trips/${props.tripUuid}`;
      successMessage.value = 'The trip has been updated!';
    } else {
      response = await $fetch('/api/trips', { method: 'post', body, headers });
      nextPath = `/trips/${response.uuid}`;
      successMessage.value = 'The trip has been created!';
    }

    await navigateTo({
      path: nextPath,
    });
  } catch (error) {
    errorMessage.value = 'Uh oh, something went wrong. Please try again later.';
  } finally {
    loading.value = false;
  }
}
</script>

<template>
  <div class="max-w-sm">
    <div v-if="loading">
      <Loader />
    </div>
    <div v-else-if="successMessage">
      <Alert type="success">
        {{ successMessage }}
      </Alert>
    </div>
    <div v-else>
      <Alert v-if="errorMessage" type="error">
        {{ errorMessage }}
      </Alert>

      <form v-on:submit.prevent="updateTrip">
        <div class="mb-8">
          <Input label="Name" type="text" add-class="w-full" v-model="name" required />
        </div>

        <PrimaryButton type="submit">Submit</PrimaryButton>
      </form>
    </div>
  </div>
</template>

<style scoped></style>
