// components/TripSelect.tsx
import { fetchWithToken } from '@/lib/fetcher';
import supabase from '@/lib/supabase';
import tripRange from '@/lib/tripRange';

export default function TripSelect({ value, onChange }) {
  // Get current session
  const session = supabase.auth.session();

  const { data, error, isLoading } = fetchWithToken('/api/trips', session?.access_token);

  function displayRange(dateRange) {
    return dateRange ? `(${dateRange})` : '';
  }

  if (isLoading) {
    return (
      <div>Loading...</div>
    )
  }
  return (
    <div>
      <select
        value={value}
        onChange={onChange}
        className="bg-gray-200 border-2 outline-none p-2 rounded-md text-gray-700 text-sm w-full"
        required
      >
        {data.map((trip) => (
          <option key={trip.uuid} value={trip.uuid}>
            {trip.name} {displayRange(tripRange(trip.start, trip.end))}
          </option>
        ))}
      </select>
    </div>
  );
}

// components/TripSelect.vue
<script lang="ts">
export default {
  props: ['modelValue'],
  emits: ['update:modelValue'],
  data() {
    return {
      trips: null,
    };
  },
  async mounted() {
    const { $supabase } = useNuxtApp();

    // Get current session
    const session = $supabase.auth.session();

    const { data, refresh } = await useFetch('/api/trips', {
      headers: { Authorization: `Bearer ${session.access_token}` },
    });

    this.trips = data;

    // Need to refresh in case trip was just created
    refresh();
  },
  methods: {
    displayRange(dateRange) {
      return dateRange ? `(${dateRange})` : '';
    },
  },
};
</script>

<template>
  <div>
    <select
      v-bind:value="modelValue"
      v-on:input="$emit('update:modelValue', $event.target.value)"
      class="bg-gray-200 border-2 outline-none p-2 rounded-md text-gray-700 text-sm w-full"
      required
    >
      <option v-for="trip in trips" v-bind:key="trip.uuid" v-bind:value="trip.uuid">
      {{ trip.name }} {{ displayRange($tripRange(trip.start, trip.end)) }}</option>
    </select>
  </div>
</template>

<style scoped></style>
