// components/User.vue
<script lang="ts" setup>
import 'material-icons/iconfont/material-icons.css';

const { $supabase } = useNuxtApp();

const user = ref($supabase.auth.user());

// Detect log in/out
$supabase.auth.onAuthStateChange((event) => {
  if (event === 'SIGNED_IN') {
    user.value = $supabase.auth.user();

    return null;
  }

  if (event === 'SIGNED_OUT') {
    user.value = null;

    return navigateTo('/login');
  }

  return null;
});

async function logout() {
  await $supabase.auth.signOut();

  return navigateTo('/login');
}
</script>

<template>
  <div v-if="user">
    <NuxtLink
      to="/profile"
      class="align-middle mr-2 text-gray-500 hover:text-gray-600 text-sm" title="Edit Profile"
    >
      {{ user.email}}
    </NuxtLink>

    <span
      v-on:click="logout"
      class="align-middle cursor-pointer material-icons pr-2
      !text-xl text-gray-400 hover:text-gray-500"
      title="Log Out">
      logout
    </span>
  </div>
  <div v-else class="text-gray-500 text-sm">
    <NuxtLink to="/register" class="hover:text-gray-600">Register</NuxtLink> |
    <NuxtLink to="/login" class="hover:text-gray-600">Log In</NuxtLink>
  </div>
</template>

<style scoped></style>

// components/User.tsx
import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import supabase from '@/lib/supabase';
import Link from 'next/link';
import 'material-icons/iconfont/material-icons.css';

export default function User() {
  const [user, setUser] = useState(null);
  const router = useRouter();

  useEffect(() => {
    setUser(supabase.auth.user());
  }, []);

  // Detect log in/out
  supabase.auth.onAuthStateChange((event) => {
    if (event === 'SIGNED_IN') {
      setUser(supabase.auth.user());

      return null;
    }

    if (event === 'SIGNED_OUT') {
      setUser(null);

      return router.push('/login');
    }

    return null;
  });

  async function logout() {
    await supabase.auth.signOut();
  
    return router.push('/login');
  }

  if (user) {
    return (
      <div>
        <Link
          href="/profile"
          className="align-middle mr-2 text-emerald-500 hover:text-emerald-400 text-sm" title="Edit Profile"
        >
          {user.email}
        </Link>

        <span
          onClick={logout}
          className="align-middle cursor-pointer material-icons pr-2
          !text-xl text-emerald-500 hover:text-emerald-400"
          title="Log Out">
          logout
        </span>
      </div>
    );
  }

  return (
    <div className="text-gray-500 text-sm">
      <Link href="/register" className="text-emerald-500 hover:text-emerald-400">Register</Link>
      <span> | </span>
      <Link href="/login" className="text-emerald-500 hover:text-emerald-400">Log In</Link>
    </div>
  );
}
