// pages/reset.vue
<script lang="ts" setup>
const { $supabase } = useNuxtApp();

const email = ref(null);

const loading = ref(false);
const successMessage = ref(null);
const errorMessage = ref (null);

async function reset() {
  try {
    errorMessage.value = null;
    loading.value = true;

    await $supabase.auth.api.resetPasswordForEmail(email.value);

    successMessage.value = 'If the email is associated with an account, you will receive a link shortly.';
  } catch (error) {
    // Return success regardless
    successMessage.value = 'If the email is associated with an account, you will receive a link shortly.';
  } finally {
    loading.value = false;
  }
}

useHead({
  title: 'Reset Password',
});
</script>

<template>
  <div>
    <PageTitle>Reset Password</PageTitle>

    <div v-if="loading">
      <Loader />
    </div>
    <div v-else-if="successMessage">
      <Alert type="success">
        {{ successMessage }}
      </Alert>
    </div>
    <div v-else>
      <Alert v-if="errorMessage" type="error">
        {{ errorMessage }}
      </Alert>

      <form v-on:submit.prevent="reset">
        <Input type="email" label="Email" add-class="mb-6" v-model="email" required />

        <Button type="submit">Reset</Button>
      </form>
    </div>
  </div>
</template>

<style scoped></style>

// pages/reset.tsx
import { useState } from 'react';
import supabase from '@/lib/supabase';
import Alert from '@/components/Alert';
import Input from '@/components/Input';
import Loader from '@/components/Loader';
import PageTitle from '@/components/PageTitle';
import PrimaryButton from '@/components/PrimaryButton';

export default function Reset() {
  const [loading, setLoading] = useState(false);
  const [successMessage, setSuccessMessage] = useState('');
  const [errorMessage, setErrorMessage] = useState('');

  const [email, setEmail] = useState('');

  async function reset(e) {
    e.preventDefault();

    try {
      setLoading(true);
      setErrorMessage('');
  
      await supabase.auth.api.resetPasswordForEmail(email);
  
      setSuccessMessage('If the email is associated with an account, you will receive a link shortly.');
    } catch (error) {
      // Return success regardless
      setSuccessMessage('If the email is associated with an account, you will receive a link shortly.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <>
      <PageTitle addClass="mb-6">Reset Password</PageTitle>

      {loading ? (
        <Loader />
      ) : successMessage ? (
        <Alert type="success">
          {successMessage}
        </Alert>
      ) : (
        <>
          {errorMessage &&
            <Alert type="error">
              {errorMessage}
            </Alert>
          }

          <form onSubmit={reset}>
            <Input type="email" label="Email" addClass="mb-6" value={email} onChange={e => setEmail(e.target.value)} required />

            <PrimaryButton type="submit">Reset</PrimaryButton>
          </form>
        </>
      )}
    </>
  );
}
